baseURL: 'https://www.matthewgirdler.com/'
languageCode: "en-us"
title: "Matt Girdler"
theme: hugo-profile

Paginate: 3
# googleAnalytics: G-DWJJVE27WD

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blogs
      url: /blogs
      weight: 1
    
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Matt Girdler"
  description: My résumé and blog
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

    menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
      disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi! my name is"
    title: "Matt."
    subtitle: "I build things for the web"
    content: "A passionate full-stack software engineer, I enjoy exploring emerging technology, collaborating with others and building robust services that focus on the user first."    
    image: /images/Portrait-Large.png
    button:
      enable: true
      name: "Résumé"
      url: "#"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/mattgirdler
        - icon: fab fa-twitter
          url: https://twitter.com/mattgirdler
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/matt-girdler-5740a3a7/
      # customIcons:
      #   - icon: /fav.png
      #     url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.jpg"
    content: |-
      I'm a software engineer with a passion for innovation. I have a background in computer science and a special interest in CI/CD, cloud computing and user-centered design My hobbies include football, game development, pixel art and music.
      
      I'm currently working as a Senior Software Engineer at [Rowe IT.](https://roweit.co.uk) in Plymouth, UK. 
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Python"
        - "Terraform"
        - "AWS"
        - "Azure"
        - "Node"
        - "React"
        - "Web3"
        - "Solidity"

  # Experience
  experience:
    enable: true
    items:
      - job: "Senior Software Engineer"
        company: "Rowe IT"
        companyUrl: "https://roweit.co.uk"
        date: "Apr 2021 - Present"
        # featuredLink:
        #   enable: true
        #   url: "https://example.com"
        # info:
        #   enable: true
        #   content: I worked as a software developer for more than one year in Amazon.
        content: |
          Consulting with various public bodies, helping them to build secure, resilient and cost-effective services. 
          Clients I've worked with include MoD, UK Hydrographic Office, Forestry Commission, Scottish Qualification Authority and Crown Commercial Services.

          - Architected, developed and maintained a payment processing system, utilising AWS Serverless architecture.
          - Various research and development activities.
          - Troubleshooting and resolving issues in legacy systems.
          - Started DevOps community of practice.
          - Coaching and mentoring.          

      - job: "Senior Software Engineer"
        company: "HM Land Registry"
        companyUrl: "https://www.gov.uk/government/organisations/land-registry"
        date: "Sep 2014 - Mar 2021"
        featuredLink:
          enable: true
          name: "View the project"
          url: "https://hmlandregistry.blog.gov.uk/tag/digital-street/"
        content: |
          I began my career at [HM Land Registry](https://www.gov.uk/government/organisations/land-registry) as a placement student.
          I gained a wide range of experience working across different teams and departments, from Data Warehousing to Security Admin, before eventually settling into my passion of Software Development.

          - Tech Lead for Casework Workflow system.
          - Lead developer for research and development project, Digital Street. 
          - Senior developer for a knowledge management system.
          - Full-stack developer for Head Office file management system.
          - Frontend developer for the Local Land Charges service.
          - IT Student Placement - Security Admin, ETL teams.

  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "BSc (Hons) Computing"
        school:
          name: "University of Plymouth"
          url: "https://www.plymouth.ac.uk/"
        date: "2012 - 2016"
        # GPA: "3.8 out of 5.0"
        content: |-
          Bachelor's degree in Computing, specialising in software development, web development and software design.
      - title: "Level 3 BTEC Computing and Games Development"
        school:
          name: "City College Plymouth"
          url: "https://www.cityplym.ac.uk/"
        date: "2010 - 2012"
        # GPA: "3.9 out of 5.0"
        content: |-
          First introduction to software development and user-centered design.
        # featuredLink:
        #   enable: true
        #   name: "My academic record"
        #   url: "https://example.com"

  # Achievements
  achievements:
    enable: true
    items:
      - title: AWS Solutions Architect (Associate)
        content: Amazon Web Services (AWS)
        url: https://www.credly.com/badges/5e4d05a4-a0cd-4112-ad84-676ee470438e
      - title: Corda Certified Developer
        content: R3
        url: https://www.credly.com/badges/e85688fc-e25d-48ad-b745-32104664f38c
      # - content: 
      - title: Foundation Certificate in Agile 
        content: BCS, The Chartered Institute for IT        
        url: 
      - title: ISO/IEC 20000 Masterclass
      - title: Codewars - 3kyu
        content: Reached rank 3kyu on Codewars
        url: https://www.codewars.com/users/mattgirdler

  # projects
  projects:
    enable: true
    items:
      - title: Social Rebels
        content: A custom e-Commerce website, developed with the Wagtail Python framework.
        image: /images/projects/SocialRebels.png
        featured:
          name: Social Rebels
          link: https://social-rebels.com
        badges:
          - "Python"
          - "Django"
          - "Bootstrap"
          - "JavaScript"          
        links:
          - icon: fa fa-instagram
            url: https://www.instagram.com/social.rebels/
          - icon: fab fa-pinterest
            url: https://www.pinterest.co.uk/SocialRebels/

      - title: Untitled Web3 Project
        content: A Web3 application, consisting of Solidity smart contracts, React frontend and NestJS REST API.
        image: /images/projects/profile2.jpg
        # featured:
        #   name: Demo
        #   link: https://django-converter.herokuapp.com
        badges:
          - "Solidity"
          - "Web3"
          - "React"
          - "NestJS"
        # links:
        #   - icon: fab fa-github
        #     url: https://github.com/gurusabarish/converter

  #Contact
  contact:
    enable: false
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: matthewdgirdler@gmail.com
    btnName: Mail me

  footer:
    # recentPosts: false
    socialNetworks:
      github: https://github.com/mattgirdler
      linkedin: https://www.linkedin.com/in/matt-girdler-5740a3a7/
      twitter: https://twitter.com/mattgirdler
